# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BdClaim < Formula
  desc "Atomic issue claim CLI for multi-agent local swarms using Beads"
  homepage "https://github.com/ccheney/bd-claim"
  version "1.0.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/ccheney/bd-claim/releases/download/v1.0.0/bd-claim_1.0.0_darwin_arm64.tar.gz"
    sha256 "5342db597d766d1136a8065890b3e96cb347dfc905c87bb1fbcc4d9881643e33"

    def install
      bin.install "bd-claim"
    end
  end

  test do
    system "#{bin}/bd-claim", "--version"
  end
end
